## @section Common parameters

## Number of Spark history server replicas to deploy
##
## @param replicaCount Number of Spark history server replicas to deploy
replicaCount: 1

## Spark history server image version
## ref: https://github.com/HivemindTechnologies/spark-history-server/pkgs/container/spark-history-server/versions
##
## @param image.repository Spark history server image name
## @param image.tag Spark history server image pull policy
## @param image.pullPolicy Spark history server image tag
image:
  repository: ghcr.io/hivemindtechnologies/spark-history-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## @param imagePullSecrets Specify docker-registry secret names as an array
## @param nameOverride Override the name of the Spark history server
## @param fullnameOverride Override the fullname of the Spark history server
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## Service account configuration
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
## @param serviceAccount.create Specifies whether a service account should be created
## @param serviceAccount.name Specifies the name of the service account to use.
## @param serviceAccount.annotations Specifies annotations to add to the service account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## @param podAnnotations Specifies annotations to add to the Spark history server pods
podAnnotations: {}

## Spark history server pods' SecurityContext
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
## @param podSecurityContext Specifies security context that will be applied to the Spark history server pods
podSecurityContext:
  {}
  # fsGroup: 2000

## Spark history server pods' Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
## @param securityContext Specifies security context that will be applied to the Spark history server containers
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @section Networking parameters

## Spark history server service
## ref: https://kubernetes.io/docs/concepts/services-networking/service/
##
## @param service.type Specifies the type of service to create
## @param service.port Specifies the port to expose
service:
  type: ClusterIP
  port: 80

## Spark history server ingress
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
## @param ingress.enabled Specifies whether to create an ingress
## @param ingress.className Specifies the class of the ingress
## @param ingress.annotations Specifies annotations to add to the ingress
## @param ingress.hosts Specifies the hostnames to map to the ingress
## @param ingress.tls Specifies TLS configuration for the ingress
ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    []
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls:
    []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

## @section Deployment parameters

## Spark history server resources
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
##
## @param resources Specifies resources to request for the Spark history server
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Spark history server node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
## @param nodeSelector Specifies node selector for the Spark history server
nodeSelector: {}

## @param tolerations Specifies the tolerations to add to the Spark history server pods
tolerations: []

## @param affinity Specifies the affinity to add to the Spark history server pods
affinity: {}

## @section Spark history server configuration
##
## @param historyServer.logPath Specifies the path to the Spark log files
historyServer:
  logPath: "s3a://my-bucket/spark-logs"
